:bug: Fix crash when trying to install dependencies
Using the `--system` flag raises an "externally managed" error:

`Using Python 3.12.3 environment at: /usr
error: The interpreter at /usr is externally managed, and indicates the following`

I have tried adding the `--break-system-packages` flag to force an installation, but that
caused other errors.

For now, using a virtual environment seems to work. Not entirely sure why it was previously
installed globally?